resources:
- bases/cache.redis.example.com_redisclusters.yaml
- bases/cache.redis.example.com_redisusers.yaml
#+kubebuilder:scaffold:crdkustomizeresource

#+kubebuilder:scaffold:crdkustomizewebhookpatch

#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
