apiVersion: database.postgres.example.com/v1alpha1
kind: PostgresCluster
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgrescluster-sample
spec:
  replicas: 3
  version: "16"
  storage:
    size: 10Gi
  ha:
    minAvailable: 2
    antiAffinityMode: preferred
