apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch-operator
    app.kubernetes.io/managed-by: kustomize
  name: elasticsearchcluster-editor-role
rules:
- apiGroups:
  - search.elasticsearch.example.com
  resources:
  - elasticsearchclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - search.elasticsearch.example.com
  resources:
  - elasticsearchclusters/status
  verbs:
  - get
