//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *MongoBackupPolicy) DeepCopyInto(out *MongoBackupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}
func (in *MongoBackupPolicy) DeepCopy() *MongoBackupPolicy {
	if in == nil { return nil }
	out := new(MongoBackupPolicy); in.DeepCopyInto(out); return out
}
func (in *MongoBackupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *MongoBackupPolicyList) DeepCopyInto(out *MongoBackupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoBackupPolicy, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}
func (in *MongoBackupPolicyList) DeepCopy() *MongoBackupPolicyList {
	if in == nil { return nil }
	out := new(MongoBackupPolicyList); in.DeepCopyInto(out); return out
}
func (in *MongoBackupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *MongoBackupPolicySpec) DeepCopyInto(out *MongoBackupPolicySpec) { *out = *in }
func (in *MongoBackupPolicySpec) DeepCopy() *MongoBackupPolicySpec {
	if in == nil { return nil }
	out := new(MongoBackupPolicySpec); in.DeepCopyInto(out); return out
}

func (in *MongoBackupPolicyStatus) DeepCopyInto(out *MongoBackupPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.NextBackupTime != nil {
		in, out := &in.NextBackupTime, &out.NextBackupTime
		*out = (*in).DeepCopy()
	}
}
func (in *MongoBackupPolicyStatus) DeepCopy() *MongoBackupPolicyStatus {
	if in == nil { return nil }
	out := new(MongoBackupPolicyStatus); in.DeepCopyInto(out); return out
}
