resources:
- bases/search.elasticsearch.example.com_elasticsearchclusters.yaml
- bases/search.elasticsearch.example.com_elasticsearchindices.yaml
#+kubebuilder:scaffold:crdkustomizeresource

#+kubebuilder:scaffold:crdkustomizewebhookpatch

#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
