apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mongodb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongobackuppolicy-editor-role
rules:
- apiGroups:
  - backup.mongodb.example.com
  resources:
  - mongobackuppolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.mongodb.example.com
  resources:
  - mongobackuppolicies/status
  verbs:
  - get
