resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_reader_clusterrole.yaml
- metrics_service.yaml
- mongocluster_editor_role.yaml
- mongocluster_viewer_role.yaml
- backup_mongobackuppolicy_editor_role.yaml
- backup_mongobackuppolicy_viewer_role.yaml
